# Query2
# This query increases in complexity: 3 classes and 3 properties are involved. Additionally, 
# there is a triangular pattern of relationships between the objects involved.
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?X ?Y ?Z
WHERE
{ 
  ?B rdfs:subClassOf ub:Student .
  ?X rdf:type ?B .
  ?A rdfs:subPropertyOf ub:memberOf .
  ?X ?A ?Z .
  ?X ub:undergraduateDegreeFrom ?Y .
  ?Y rdf:type ub:University .
  ?Z rdf:type ub:Department .
  ?Z ub:subOrganizationOf ?Y
}
